#!/usr/bin/env python3
"""Turns the specification's presence card test vectors into a C header for tests/card.c.

    python3 tests/vectors/cards_to_c.py tests/vectors/cards.json OUT.h

The build runs this; nothing it writes is checked in. Like the others it only reformats: every
value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def hexbytes(h):
    return "{" + ", ".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


def blob(h):
    """Bytes of any length, with their count; an empty one still has to be an array in C."""
    return f"(const uint8_t[]){hexbytes(h) if h else '{0}'}, {len(h) // 2}"


def text(s):
    """A C string literal of UTF-8 bytes, each escaped, so the header is ASCII."""
    return '"' + "".join(f"\\x{b:02x}" for b in s.encode("utf-8")) + '"'


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    L = ["/* Generated by tests/vectors/cards_to_c.py from tests/vectors/cards.json. Do not edit. */", ""]
    L.append(f"static const uint8_t self_address[32] = {hexbytes(v['self'])};")
    L.append(f"static const uint8_t relayed[] = {hexbytes(v['relayed_still_valid'])};")

    L.append("static const struct accepted_case accepted[] = {")
    L += [f"    {{{hexbytes(c['seed'])}, {hexbytes(c['address'])}, {c['number']}u, {text(c['name'])}, "
          f"{len(c['name'].encode('utf-8'))}, {c['hops']}, {c['power']}, {blob(c['signed'])}, "
          f"{blob(c['frame'])}}},"
          for c in v["accepted"]]
    L.append("};")

    L.append("static const struct rejected_case rejected[] = {")
    L += [f"    {{\"{c['why']}\", {blob(c['frame'])}}}," for c in v["rejected"]]
    L.append("};")

    L.append("static const struct delivery_case deliveries[] = {")
    L += [f"    {{{blob(c['frame'])}, {'true' if c['keep'] else 'false'}}}," for c in v["deliveries"]]
    L.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
