#!/usr/bin/env python3
"""Turns the specification's companion protocol vectors into a C header for tests/companion.c.

    python3 tests/vectors/companion_to_c.py tests/vectors/companion.json OUT.h [exchange]

With `exchange`, it writes the exchange alone, for tests/link.c, which needs nothing else.

The build runs this; nothing it writes is checked in. Like the other converters it only
reformats: every value in the header is copied from the JSON, none is computed. A frame's fields
become a struct tern_companion_msg, with the draft's names folded as tern/companion.h folds them.
"""

import json
import sys

TYPES = {
    "HELLO": 0x01, "SYNC": 0x02, "PING": 0x03, "SET_TIME": 0x04, "SET": 0x05, "SEND": 0x10,
    "READ": 0x11, "SAVE_CONTACT": 0x18, "REMOVE_CONTACT": 0x19, "END_SESSION": 0x1A, "OK": 0x40,
    "ERROR": 0x41,
    "INFO": 0x42, "SYNCED": 0x43, "QUEUED": 0x44, "SELF": 0x80, "CONTACT": 0x81,
    "CONTACT_GONE": 0x82, "MESSAGE": 0x83, "STATE": 0x84, "NEIGHBOUR": 0x85,
    "NEIGHBOUR_GONE": 0x86, "AIRTIME": 0x87, "POWER": 0x88, "ASKED": 0x89,
    "MAKE_GROUP": 0x20, "LEAVE_GROUP": 0x21, "NAME_GROUP": 0x22, "SEND_GROUP": 0x23,
    "SEND_INVITE": 0x24, "JOIN": 0x25, "MADE": 0x45, "GROUP": 0x8A, "GROUP_GONE": 0x8B,
    "GROUP_MESSAGE": 0x8C, "INVITE": 0x8D, "UPDATE_BEGIN": 0x30, "UPDATE_DATA": 0x31,
    "UPDATE_END": 0x32, "UPDATING": 0x46, "SET_POSITION": 0x33, "SHARE": 0x34,
    "SHARE_GROUP": 0x35, "POSITION": 0x8E, "GROUP_POSITION": 0x8F, "SHARING": 0x90,
    "GROUP_SHARING": 0x91, "CARD": 0x92, "CARD_GONE": 0x93,
}
STRINGS = ("text", "name", "firmware", "region")
ADDRESSES = ("to", "address", "contact")
OWN_STRINGS = ("board", "release", "card_name")  # strings with members of their own
RENAMED = {"snr_quarter_db": "snr"}
SET_VALUE = {1: "region", 2: "role", 3: "power", 4: "passkey", 5: "cards", 6: "text"}


def hexbytes(h):
    if not h:
        return "{0}"
    return "{" + ", ".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


def msg(kind, seq, fields):
    parts = [f".type = 0x{TYPES[kind]:02x}", f".seq = {seq}"]
    for name, value in fields.items():
        if kind == "SET" and name == "value":
            name = SET_VALUE[fields["setting"]]
        if name in STRINGS:
            raw = value.encode("utf-8").hex()
            parts.append(f".text_len = {len(raw) // 2}")
            if raw:
                parts.append(f".text = {hexbytes(raw)}")
        elif name in OWN_STRINGS:
            raw = value.encode("utf-8").hex()
            parts.append(f".{name}_len = {len(raw) // 2}")
            if raw:
                parts.append(f".{name} = {hexbytes(raw)}")
        elif name == "data":
            parts.append(f".data_len = {len(value) // 2}")
            if value:
                parts.append(f".data = {hexbytes(value)}")
        elif name == "digest":
            parts.append(f".digest = {hexbytes(value)}")
        elif name in ADDRESSES:
            parts.append(f".address = {hexbytes(value)}")
        elif name == "group":
            parts.append(f".group = {hexbytes(value)}")
        else:
            parts.append(f".{RENAMED.get(name, name)} = {value}")
    return "{" + ", ".join(parts) + "}"


def blob(h):
    return f"{hexbytes(h)}, {len(h) // 2}"


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    L = ["/* Generated by tests/vectors/companion_to_c.py from tests/vectors/companion.json. Do not edit. */", ""]
    if sys.argv[3:] != ["exchange"]:
        cases(L, v)
    exchange(L, v)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


def cases(L, v):
    c = v["crc_check"]
    L.append(f"static const uint8_t crc_input[] = {hexbytes(c['input'])};")
    L.append(f"static const uint16_t crc_expected = {c['crc']};")

    L.append("static const struct frame_case frames[] = {")
    L += [
        f"    {{{msg(f['type'], f['seq'], f['fields'])}, {blob(f['frame'])}, {blob(f['stream'])}}},"
        for f in v["frames"]
    ]
    L.append("};")

    L.append("static const struct extended_case extended[] = {")
    L += [
        f"    {{{msg(e['type'], e['seq'], e['fields'])}, {blob(e['frame'])}}},"
        for e in v["extended"]
    ]
    L.append("};")

    L.append("static const struct group_id_case group_ids[] = {")
    L += [f"    {{{hexbytes(g['group_secret'])}, {hexbytes(g['group'])}}}," for g in v["group_ids"]]
    L.append("};")

    L.append("static const struct rejected_case rejected[] = {")
    L += [
        f"    {{\"{r['why']}\", {blob(r['frame'])}, {-1 if r['answer'] is None else r['answer']}}},"
        for r in v["rejected"]
    ]
    L.append("};")

    for i, s in enumerate(v["streams"]):
        items = ", ".join(
            f"{{{'true' if 'frame' in it else 'false'}, {blob(it.get('frame', it.get('text')))}}}"
            for it in s["items"]
        )
        L.append(f"static const struct item stream_items_{i}[] = {{{items}}};")
    L.append("static const struct stream_case streams[] = {")
    L += [
        f"    {{\"{s['why']}\", {blob(s['stream'])}, stream_items_{i}, {len(s['items'])}, "
        f"{blob(s['pending'])}}},"
        for i, s in enumerate(v["streams"])
    ]
    L.append("};")


def exchange(L, v):
    """The exchange, and each earlier version's connection as older_<version>, with the two
    groups' secrets; and the update's two connections as update_0 and update_1, its refusals,
    and its image."""
    L.append(f"static const uint8_t made_secret[16] = {hexbytes(v['made'])};")
    L.append(f"static const uint8_t invited_secret[16] = {hexbytes(v['invited'])};")
    L.append(f"static const uint8_t update_image[] = {hexbytes(v['image'])};")
    L.append(f"static const uint8_t update_digest[32] = {hexbytes(v['image_digest'])};")
    runs = [("exchange", v["exchange"])] + [(f"older_{o['version']}", o["frames"]) for o in v["older"]]
    runs += [(f"update_{i}", c) for i, c in enumerate(v["update"])] + [("refusals", v["refusals"])]
    for name, frames in runs:
        L.append(f"static const struct step {name}[] = {{")
        L += [
            f"    {{{'true' if e['from'] == 'client' else 'false'}, {blob(e['frame'])}}},"
            for e in frames
        ]
        L.append("};")


if __name__ == "__main__":
    main()
