#!/usr/bin/env python3
"""Turns the specification's first-contact test vectors into a C header for tests/contact.c.

    python3 tests/vectors/contact_to_c.py tests/vectors/first-contact.json OUT.h

The build runs this; nothing it writes is checked in. Like unicast_to_c.py it only reformats:
every value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def c_bytes(hex_str):
    b = bytes.fromhex(hex_str)
    body = ", ".join(f"0x{x:02x}" for x in b)
    return f"(const uint8_t[]){{{body}}}, {len(b)}"


def c_array(hex_str, n):
    b = bytes.fromhex(hex_str)
    assert len(b) == n, (hex_str, n)
    return "{" + ", ".join(f"0x{x:02x}" for x in b) + "}"


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    lines = [
        "/* Generated by tests/vectors/contact_to_c.py from tests/vectors/first-contact.json."
        " Do not edit. */",
        "",
    ]

    lines.append("static const struct address_case addresses[] = {")
    for c in v["addresses"]:
        lines.append(
            f"    {{{c_array(c['seed'], 32)}, {c_array(c['address'], 32)}, "
            f"{c_array(c['x25519_private'], 32)}, {c_array(c['x25519_public'], 32)}}},"
        )
    lines.append("};")

    lines.append("static const struct rejected_address_case rejected_addresses[] = {")
    for c in v["rejected_addresses"]:
        lines.append(f"    {{{json.dumps(c['reason'])}, {c_array(c['address'], 32)}}},")
    lines.append("};")

    names = [h["name"] for h in v["handshakes"]]
    lines.append("static const struct handshake_case handshakes[] = {")
    for h in v["handshakes"]:
        frames = ", ".join(f"{{{c_bytes(f)}}}" for f in h["frames"])
        lines.append(
            f"    {{{json.dumps(h['name'])}, {c_array(h['initiator_seed'], 32)}, "
            f"{c_array(h['responder_seed'], 32)}, {c_array(h['initiator_ephemeral'], 32)}, "
            f"{c_array(h['responder_ephemeral'], 32)}, 0x{h['c_i']}, 0x{h['c_r']}, "
            f"{{{frames}}}, {c_array(h['session_secret'], 32)}}},"
        )
    lines.append("};")

    lines.append("static const struct not_for_me_case not_for_me[] = {")
    for c in v["not_for_me"]:
        lines.append(f"    {{{json.dumps(c['name'])}, {c_array(c['responder_seed'], 32)}, "
                     f"{c_bytes(c['frame'])}}},")
    lines.append("};")

    lines.append("static const struct source_case sources[] = {")
    for c in v["sources"]:
        lines.append(f"    {{{json.dumps(c['name'])}, {c_array(c['responder_seed'], 32)}, "
                     f"{c_array(c['responder_ephemeral'], 32)}, 0x{c['c_r']}, "
                     f"{c_bytes(c['frame'])}, {c['source']}u, {{{c_bytes(c['reply'])}}}}},")
    lines.append("};")

    lines.append("static const struct rejected_case rejected[] = {")
    for c in v["rejected"]:
        lines.append(f"    {{{json.dumps(c['name'])}, {names.index(c['handshake'])}, "
                     f"{c['message']}, {c_bytes(c['frame'])}}},")
    lines.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
