#!/usr/bin/env python3
"""Turns the specification's flooding test vectors into a C header for tests/flood.c.

    python3 tests/vectors/flooding_to_c.py tests/vectors/flooding.json OUT.h

The build runs this; nothing it writes is checked in. Like unicast_to_c.py it only reformats:
every value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def hexbytes(h):
    return "{" + ", ".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


def blob(h):
    """Bytes of any length, with their count; an empty one still has to be an array in C."""
    return f"(const uint8_t[]){hexbytes(h) if h else '{0}'}, {len(h) // 2}"


def b(v):
    return "true" if v else "false"


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    L = ["/* Generated by tests/vectors/flooding_to_c.py from tests/vectors/flooding.json. Do not edit. */", ""]

    L.append("static const struct head_case heads[] = {")
    L += [f"    {{{c['hdr']}, {c['hops']}, {c['power']}, {hexbytes(c['id'])}, {blob(c['frame'])}}},"
          for c in v["heads"]]
    L.append("};")

    L.append("static const struct rejected_case rejected[] = {")
    L += [f"    {{\"{c['name']}\", {blob(c['frame'])}}}," for c in v["rejected"]]
    L.append("};")

    L.append("static const struct same_case same_cases[] = {")
    L += [f"    {{\"{c['name']}\", {blob(c['a'])}, {blob(c['b'])}, {b(c['same'])}}}," for c in v["same"]]
    L.append("};")

    L.append("static const struct pass_case pass_cases[] = {")
    L += [f"    {{{b(c['role'] == 'relay')}, {c['relay_neighbours']}, {c['hops']}, "
          f"{-1 if c['sends'] is None else c['sends']}}}," for c in v["passes"]]
    L.append("};")

    L.append("static const struct copy_case copy_cases[] = {")
    L += [f"    {{{c['received']}, {b(c['drops'])}}}," for c in v["copies"]]
    L.append("};")

    L.append("static const struct wait_case wait_cases[] = {")
    L += [f"    {{{c['spreading_factor']}, {c['bandwidth_hz']}u, {c['length']}, {c['airtime_ns']}LL, "
          f"{c['longest_ns']}LL}}," for c in v["waits"]]
    L.append("};")

    L.append("static const struct power_case power_cases[] = {")
    for c in v["powers"]:
        floors = ", ".join("TERN_FLOOD_FLOOR_UNKNOWN" if f is None else str(f)
                           for f in c["floors_sixteenths"])
        L.append(f"    {{{c['every']}, (const int32_t[]){{{floors or '0'}}}, "
                 f"{len(c['floors_sixteenths'])}, {c['lowest']}, {c['full']}, {c['power']}}},")
    L.append("};")

    # Ids in the vectors are names: each becomes the eight bytes of its place in the case.
    for i, c in enumerate(v["seen"]):
        names = {}
        for t in c["takes"]:
            names.setdefault(t["id"], len(names) + 1)
        for a in c["asks"]:
            names.setdefault(a["id"], len(names) + 1)
        takes = ", ".join(f"{{{t['at_ns']}LL, {names[t['id']]}}}" for t in c["takes"])
        asks = ", ".join(f"{{{a['at_ns']}LL, {names[a['id']]}, {b(a['seen'])}}}" for a in c["asks"])
        L.append(f"static const struct seen_take seen_takes_{i}[] = {{{takes}}};")
        L.append(f"static const struct seen_ask seen_asks_{i}[] = {{{asks}}};")
    L.append("static const struct seen_case seen_cases[] = {")
    L += [f"    {{\"{c['name']}\", seen_takes_{i}, {len(c['takes'])}, seen_asks_{i}, {len(c['asks'])}}},"
          for i, c in enumerate(v["seen"])]
    L.append("};")

    for i, c in enumerate(v["allowances"]):
        frames = ", ".join(f"{{{f['at_ns']}LL, {f['airtime_ns']}LL, {b(f['pays'])}}}" for f in c["frames"])
        L.append(f"static const struct allowance_frame allowance_frames_{i}[] = {{{frames}}};")
    L.append("static const struct allowance_case allowance_cases[] = {")
    L += [f"    {{\"{c['name']}\", {c['share_ppm']}u, {c['window_s']}, {c['spreading_factor']}, "
          f"{c['bandwidth_hz']}u, allowance_frames_{i}, {len(c['frames'])}}},"
          for i, c in enumerate(v["allowances"])]
    L.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
