#!/usr/bin/env python3
"""Turns the specification's forwarding test vectors into a C header for tests/forward.c, or
its listens alone into one for tests/listen.c.

    python3 tests/vectors/forwarding_to_c.py tests/vectors/forwarding.json OUT.h
    python3 tests/vectors/forwarding_to_c.py tests/vectors/forwarding.json OUT.h listens

The build runs this; nothing it writes is checked in. Like unicast_to_c.py it only reformats:
every value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def hexbytes(h):
    return "{" + ", ".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


def b(v):
    return "true" if v else "false"


def head(h):
    return f"{{{h['hdr']}, {h['hops']}, {h.get('power', 0)}, {h.get('next', 0)}u, {h['destination']}u}}"


RADIO = {"preamble": "PREAMBLE", "header": "HEADER", "end": "END", "sent": "SENT"}


def listens(v):
    """Each case's events and asks as arrays of their own, and the cases pointing at them."""
    L = []
    for i, c in enumerate(v["listens"]):
        events = ", ".join(f"{{{e['at_ns']}LL, {RADIO[e['radio']]}}}" for e in c["events"])
        asks = ", ".join(f"{{{a['at_ns']}LL, {b(a['receiving'])}}}" for a in c["asks"])
        # An array of no elements is not C: a case with no events has one that is never read.
        L.append(f"static const struct listen_event listen_events_{i}[] = {{{events or '{0, END}'}}};")
        L.append(f"static const struct listen_ask listen_asks_{i}[] = {{{asks}}};")
    L.append("static const struct listen_case listen_cases[] = {")
    L += [
        f"    {{{c['spreading_factor']}, {c['bandwidth_hz']}u, listen_events_{i}, {len(c['events'])}, "
        f"listen_asks_{i}, {len(c['asks'])}}},"
        for i, c in enumerate(v["listens"])
    ]
    L.append("};")
    return L


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    L = ["/* Generated by tests/vectors/forwarding_to_c.py from tests/vectors/forwarding.json. Do not edit. */", ""]
    if sys.argv[3:] == ["listens"]:
        with open(out, "w", encoding="utf-8") as f:
            f.write("\n".join(L + listens(v)) + "\n")
        return

    L.append("static const struct head_case heads[] = {")
    L += [
        f"    {{{head(c)}, {hexbytes(c['tag'])}, {hexbytes(c['frame'])}, {len(c['frame']) // 2}}},"
        for c in v["heads"]
    ]
    L.append("};")

    L.append("static const struct rejected_case rejected[] = {")
    L += [
        f"    {{\"{c['why']}\", {hexbytes(c['frame'])}, {len(c['frame']) // 2}}}," for c in v["rejected"]
    ]
    L.append("};")

    L.append("static const struct hop_case hop_cases[] = {")
    L += [
        f"    {{\"{c['why']}\", {hexbytes(c['sent'])}, {len(c['sent']) // 2}, {hexbytes(c['heard'])}, "
        f"{len(c['heard']) // 2}, {b(c['ends'])}}},"
        for c in v["hops"]
    ]
    L.append("};")

    L.append("static const struct wait_case wait_cases[] = {")
    L += [
        f"    {{\"{c['why']}\", {hexbytes(c['sent'])}, {len(c['sent']) // 2}, {b(c['listens'])}}},"
        for c in v["waits"]
    ]
    L.append("};")

    L.append("static const struct back_case backs[] = {")
    L += [
        f"    {{{c['power']}, {c['snr_quarter_db']}, {c['spreading_factor']}, {c['lowest']}, "
        f"{c['full']}, {c['needs']}}},"
        for c in v["backs"]
    ]
    L.append("};")

    L.append("static const struct power_case power_cases[] = {")
    L += [
        f"    {{{c['neighbour']}, {'INT8_MIN' if c['back'] is None else c['back']}, {c['try']}, "
        f"{c['full']}, {c['power']}}},"
        for c in v["powers"]
    ]
    L.append("};")

    L.append("static const struct again_case again_cases[] = {")
    L += [
        f"    {{{b(c['again'] == 'source')}, {c['spreading_factor']}, {c['bandwidth_hz']}u, "
        f"{c['length']}, {c['airtime_ns']}LL, {c['longest_ns']}LL}},"
        for c in v["agains"]
    ]
    L.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
