#!/usr/bin/env python3
"""Turns the specification's group test vectors into a C header for tests/group.c.

    python3 tests/vectors/groups_to_c.py tests/vectors/groups.json OUT.h

The build runs this; nothing it writes is checked in. Like unicast_to_c.py it only reformats:
every value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def hexbytes(h):
    return "{" + ", ".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


def blob(h):
    """Bytes of any length, with their count; an empty one still has to be an array in C."""
    return f"(const uint8_t[]){hexbytes(h) if h else '{0}'}, {len(h) // 2}"


def cstr(s):
    """A C string literal of text's UTF-8, every byte past ASCII's printable range escaped."""
    out = ""
    for byte in s.encode("utf-8"):
        out += chr(byte) if 0x20 <= byte < 0x7F and chr(byte) not in '"\\?' else f"\\{byte:03o}"
    return f'"{out}"'


def b(v):
    return "true" if v else "false"


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    L = ["/* Generated by tests/vectors/groups_to_c.py from tests/vectors/groups.json. Do not edit. */", ""]

    L.append("static const struct accepted_case accepted[] = {")
    for c in v["accepted"]:
        i = c["intermediate"]
        L.append(f"    {{\"{c['name']}\", {c['hdr']}, {b(c['node'])}, {hexbytes(c['group_secret'])}, "
                 f"{hexbytes(c['nonce'])}, {c['from']}u, {c['count']}u, {blob(c['content'])}, {c['hops']}, "
                 f"{c['power']}, {c['self']}u, "
                 f"{hexbytes(i['group_key'])}, {hexbytes(i['gtag'])}, {blob(c['frame'])}}},")
    L.append("};")

    L.append("static const struct rejected_case rejected[] = {")
    L += [f"    {{\"{c['name']}\", {hexbytes(c['group_secret'])}, {c['self']}u, {blob(c['frame'])}}},"
          for c in v["rejected"]]
    L.append("};")

    for i, c in enumerate(v["members"]):
        secrets = ", ".join(hexbytes(g) for g in c["groups"])
        L.append(f"static const uint8_t member_groups_{i}[][16] = {{{secrets}}};")
        ds = ", ".join(
            f"{{{blob(d['frame'])}, {b(d['accept'])}, {d.get('group', 0)}, {d.get('from', 0)}u, "
            f"{d.get('count', 0)}u, {blob(d.get('content', ''))}}}" for d in c["deliveries"])
        L.append(f"static const struct delivery member_deliveries_{i}[] = {{{ds}}};")
    L.append("static const struct member_case member_cases[] = {")
    L += [f"    {{\"{c['name']}\", {c['self']}u, member_groups_{i}, {len(c['groups'])}, "
          f"member_deliveries_{i}, {len(c['deliveries'])}}}," for i, c in enumerate(v["members"])]
    L.append("};")

    for i, c in enumerate(v["counts"]):
        ds = ", ".join(f"{{{d['from']}u, {d['count']}u, {blob(d['frame'])}, {b(d['accept'])}}}"
                       for d in c["deliveries"])
        L.append(f"static const struct counted count_deliveries_{i}[] = {{{ds}}};")
    L.append("static const struct count_case count_cases[] = {")
    L += [f"    {{\"{c['name']}\", {hexbytes(c['group_secret'])}, {c['self']}u, "
          f"{blob(c['content'])}, count_deliveries_{i}, {len(c['deliveries'])}}},"
          for i, c in enumerate(v["counts"])]
    L.append("};")

    L.append("static const struct invite_case invites[] = {")
    L += [f"    {{{hexbytes(c['group_secret'])}, {blob(c['name'].encode().hex())}, "
          f"{blob(c['plaintext'])}}}," for c in v["invites"]]
    L.append("};")

    L.append("static const struct bad_invite_case bad_invites[] = {")
    L += [f"    {{\"{c['name']}\", {blob(c['plaintext'])}}}," for c in v["bad_invites"]]
    L.append("};")

    L.append("static const struct join_case join_codes[] = {")
    for c in v["join_codes"]:
        reads = ", ".join(cstr(r) for r in c["reads"])
        L.append(f"    {{{hexbytes(c['group_secret'])}, {blob(c['name'].encode().hex())}, "
                 f"{blob(c['payload'])}, {cstr(c['link'])}, {{{reads}}}, {len(c['reads'])}}},")
    L.append("};")

    L.append("static const struct bad_join_case bad_join_codes[] = {")
    L += [f"    {{{cstr(c['why'])}, {cstr(c['link'])}}}," for c in v["bad_join_codes"]]
    L.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
