#!/usr/bin/env python3
"""Turns the specification's radio-settings test vectors into a C header for tests/region.c.

    python3 tests/vectors/phy_to_c.py tests/vectors/phy.json OUT.h

The build runs this; nothing it writes is checked in. Like unicast_to_c.py it only reformats:
every value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    lines = [
        "/* Generated by tests/vectors/phy_to_c.py from tests/vectors/phy.json. Do not edit. */",
        "",
        f"#define VECTOR_SYNC_WORD 0x{v['sync_word']}",
        f"#define VECTOR_SYNC_WORD_SX126X 0x{v['sync_word_sx126x']}",
        f"#define VECTOR_PREAMBLE {v['preamble_symbols']}",
        f"#define VECTOR_CR_DENOMINATOR {v['coding_rate_denominator']}",
        f"#define VECTOR_LENGTHS {len(v['profiles'][0]['airtime_ns'])}",
        "",
        "static const struct profile_case profiles[] = {",
    ]
    for p in v["profiles"]:
        air = ", ".join(f"{{{a['length']}, {a['ns']}}}" for a in p["airtime_ns"])
        lines.append(
            f"    {{{json.dumps(p['name'])}, {p['frequency_hz']}, {p['bandwidth_hz']}, "
            f"{p['spreading_factor']}, {p['max_eirp_dbm']}, {p['duty_cycle_ppm']}, "
            f"{p['duty_window_s']}, {{{air}}}}},"
        )
    lines.append("};")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
