#!/usr/bin/env python3
"""Turns the specification's position test vectors into a C header for tests/position.c.

    python3 tests/vectors/positions_to_c.py tests/vectors/positions.json OUT.h

The build runs this; nothing it writes is checked in. Like the other converters it only
reformats: every value in the header is copied from the JSON, none is computed. The frames and
sizes are left out: the frames are unicast-security.json's and groups.json's, checked there, and
the sizes check nothing the positions do not.
"""

import json
import sys


def hexbytes(h):
    return "{" + ", ".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


def blob(h):
    """Bytes of any length, with their count; an empty one still has to be an array in C."""
    return f"(const uint8_t[]){hexbytes(h) if h else '{0}'}, {len(h) // 2}"


def b(v):
    return "true" if v else "false"


def read(r):
    """A struct read_case's fields: what a reader gives, -1 for an optional field not there."""
    if r is None:
        return "false, {0}"
    keys = ("precision", "row", "column", "latitude", "longitude", "south", "west")
    vals = [str(r.get(k, 0)) for k in keys]
    vals += [str(r.get(k, -1)) for k in ("altitude", "accuracy", "age")]
    return "true, {" + ", ".join(vals) + "}"


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    L = ["/* Generated by tests/vectors/positions_to_c.py from tests/vectors/positions.json. Do not edit. */", ""]

    L.append("static const struct grid_case grid[] = {")
    for c in v["grid"]:
        L.append(f"    {{\"{c['name']}\", {c['latitude']}, {c['longitude']}, {c['precision']}, "
                 f"{c['row']}u, {c['column']}u, {blob(c['where'])}, {c['centre_latitude']}, "
                 f"{c['centre_longitude']}, {c['south']}, {c['west']}}},")
    L.append("};")

    L.append("static const struct position_case positions[] = {")
    for c in v["positions"]:
        opt = [str(c.get(k, -1)) for k in ("altitude", "accuracy", "age_seconds")]
        L.append(f"    {{\"{c['name']}\", {c['precision']}, {c.get('latitude', 0)}, "
                 f"{c.get('longitude', 0)}, {', '.join(opt)}, {blob(c['plaintext'])}, "
                 f"{{{read(c['read'])}}}}},")
    L.append("};")

    L.append("static const struct extended_case extended[] = {")
    L += [f"    {{{blob(c['plaintext'])}, {{{read(c['read'])}}}}}," for c in v["extended"]]
    L.append("};")

    L.append("static const struct ignored_case ignored[] = {")
    L += [f"    {{\"{c['why']}\", {blob(c['plaintext'])}}}," for c in v["ignored"]]
    L.append("};")

    L.append("static const struct age_case ages[] = {")
    L += [f"    {{{c['seconds']}u, {c['byte']}, {c['read_seconds']}u}}," for c in v["ages"]]
    L.append("};")

    for i, c in enumerate(v["receiving"]):
        L.append(f"static const struct delivery receiving_{i}[] = {{")
        L += [f"    {{{b(d['contact'])}, {d['counter']}u, {blob(d['plaintext'])}, {{{read(d['holds'])}}}}},"
              for d in c["deliveries"]]
        L.append("};")
    L.append("static const struct receiving_case receiving[] = {")
    L += [f"    {{\"{c['name']}\", receiving_{i}, {len(c['deliveries'])}}},"
          for i, c in enumerate(v["receiving"])]
    L.append("};")

    L.append("static const struct schedule_case schedule[] = {")
    for c in v["schedule"]:
        sent = c["last_at"] is not None
        L.append(f"    {{\"{c['note']}\", {c['interval']}, {b(sent)}, {c['last_at'] if sent else 0}, "
                 f"{b(c['changed'])}, {c['age']}, {c['now']}, {b(c['due'])}}},")
    L.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
