#!/usr/bin/env python3
"""Turns the specification's routing test vectors into a C header for tests/route.c.

    python3 tests/vectors/routing_to_c.py tests/vectors/routing.json OUT.h

The build runs this; nothing it writes is checked in. Like unicast_to_c.py it only reformats:
every value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def hexbytes(h):
    return "{" + ", ".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


def b(v):
    return "true" if v else "false"


def fd(f):
    return "{false, 0, 0}" if f is None else f"{{true, {f['seq']}, {f['metric']}}}"


def idx(v):
    return -1 if v is None else v


def routes(rs, cost):
    return "{" + ", ".join(f"{{{r['seq']}, {r['metric']}, {cost}}}" for r in rs) + "}"


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    L = ["/* Generated by tests/vectors/routing_to_c.py from tests/vectors/routing.json. Do not edit. */", ""]

    L.append("static const struct id_case ids[] = {")
    L += [f"    {{{hexbytes(c['address'])}, {c['id']}u}}," for c in v["ids"]]
    L.append("};")

    L.append("static const struct newer_case newers[] = {")
    L += [f"    {{{c['a']}, {c['b']}, {b(c['newer'])}}}," for c in v["newer"]]
    L.append("};")

    L.append("static const struct promise_case promises[] = {")
    L += [
        f"    {{{c['seconds']}, {c['code']}, {-1 if c['read_seconds'] is None else c['read_seconds']}}},"
        for c in v["promises"]
    ]
    L.append("};")

    L.append("static const struct announce_case announces[] = {")
    for c in v["announces"]:
        named = ", ".join(f"{{{n['id']}u, {n['margin']}}}" for n in c["neighbours"]) or "{0, 0}"
        rts = (
            ", ".join(f"{{{r['destination']}u, {r['seq']}, {r['metric']}}}" for r in c["routes"])
            or "{0, 0, 0}"
        )
        address = hexbytes(c["address"]) if c["carries_address"] else "{0}"
        L.append(
            f"    {{{{.sender = {c['sender']}u, .number = {c['number']}, .seq = {c['seq']}, "
            f".relay = {b(c['relay'])}, .starting = {b(c['starting'])}, .promise = {c['promise']}, "
            f".round = {c['round']}, .power = {c['power']}, .named_count = {len(c['neighbours'])}, "
            f".route_count = {len(c['routes'])}, .carries_address = {b(c['carries_address'])}, "
            f".address = {address}, .named = {{{named}}}, .routes = {{{rts}}}}}, "
            f"{hexbytes(c['seed'])}, {hexbytes(c['address'])}, "
            f"{len(c['frame']) // 2}, {hexbytes(c['frame'])}}},"
        )
    L.append("};")

    L.append("static const struct verified_case verifieds[] = {")
    L += [
        f"    {{{c['announce']}, {b(c['held_address'] is not None)}, "
        f"{hexbytes(c['held_address']) if c['held_address'] else '{0}'}, {b(c['takes'])}}},"
        for c in v["verified"]
    ]
    L.append("};")

    L.append("static const struct request_case requests[] = {")
    for c in v["requests"]:
        asks = ", ".join(f"{{{r['destination']}u, {r['seq']}, {r['hops']}}}" for r in c["requests"])
        L.append(
            f"    {{{{{c['next']}u, {len(c['requests'])}, {{{asks}}}}}, {len(c['frame']) // 2}, "
            f"{hexbytes(c['frame'])}}},"
        )
    L.append("};")

    L.append("static const struct rejected_case rejected[] = {")
    L += [
        f"    {{{json.dumps(c['why'])}, {len(c['frame']) // 2}, {hexbytes(c['frame'])}}},"
        for c in v["rejected"]
    ]
    L.append("};")
    # The one the reader discards for being its own: from the last address in ids.
    L.append(f"#define VECTOR_OWN_ID {v['ids'][-1]['id']}u")

    L.append("static const struct floor_case floors[] = {")
    for c in v["floors"]:
        steps = ", ".join(
            f"{{{h['power']}, {h['snr_quarter_db']}, {h['floor_sixteenths']}, {h['margin']}}}"
            for h in c["heard"]
        )
        L.append(
            f"    {{{c['spreading_factor']}, {c['full_power']}, {len(c['heard'])}, {{{steps}}}}},"
        )
    L.append("};")

    L.append("static const struct link_case links[] = {")
    L += [
        f"    {{{b(c['own_margin_sixteenths'] is not None)}, {c['own_margin_sixteenths'] or 0}, "
        f"{c['their_margin'] or 0}, {b(c['up'])}}},"
        for c in v["links"]
    ]
    L.append("};")

    L.append("static const struct named_case nameds[] = {")
    L += [
        f"    {{{c['named']}, {c['number']}, {c['round']}, {b(c['withdrawn'])}}}," for c in v["named"]
    ]
    L.append("};")

    L.append("static const struct numbering_case numberings[] = {")
    L += [
        f"    {{{c['last']}, {c['number']}, {b(c['promise_passed'])}, {b(c['starting'])}, "
        f"{b(c['was_starting'])}, {json.dumps(c['does'])}}},"
        for c in v["numbering"]
    ]
    L.append("};")

    L.append("static const struct cost_case costs[] = {")
    L += [f"    {{{json.dumps(c['profile'])}, {c['link_cost']}}}," for c in v["costs"]]
    L.append("};")

    L.append("static const struct feasible_case feasibles[] = {")
    for c in v["feasible"]:
        for r in c["routes"]:
            L.append(
                f"    {{{fd(c['feasibility_distance'])}, {r['seq']}, {r['metric']}, {b(r['feasible'])}}},"
            )
    L.append("};")

    L.append("static const struct selection_case selections[] = {")
    L += [
        f"    {{{fd(c['feasibility_distance'])}, {len(c['routes'])}, "
        f"{routes(c['routes'], c['link_cost']) if c['routes'] else '{{0, 0, 0}}'}, "
        f"{idx(c['selected'])}, {idx(c['selects'])}}},"
        for c in v["selection"]
    ]
    L.append("};")

    L.append("static const struct place_case places[] = {")
    L += [
        f"    {{{len(c['neighbours'])}, {{"
        + ", ".join(f"{{{n['floor_sixteenths']}, {b(n['up'])}}}" for n in c["neighbours"])
        + f"}}, {c['floor_sixteenths']}, {idx(c['replaces'])}}},"
        for c in v["places"]
    ]
    L.append("};")

    L.append("static const struct kept_case kepts[] = {")
    L += [
        f"    {{{fd(c['feasibility_distance'])}, {routes(c['routes'], c['link_cost'])}, "
        f"{idx(c['selected'])}, {{{c['offered']['seq']}, {c['offered']['metric']}, {c['link_cost']}}}, "
        f"{idx(c['replaces'])}}},"
        for c in v["kept"]
    ]
    L.append("};")

    L.append("static const struct default_case defaults[] = {")
    L += [
        f"    {{{len(c['neighbours'])}, {{"
        + ", ".join(
            f"{{{n['floor_sixteenths']}, {b(n['up'])}, {b(n['relay'])}}}" for n in c["neighbours"]
        )
        + f"}}, {b(c['leaf'])}, {b(c['starting'])}, {c['busy_ppm']}, {len(c['tried'])}, {{"
        + (", ".join(str(t) for t in c["tried"]) or "0")
        + f"}}, {idx(c['next'])}, {c['link_cost']}, {c['metric']}}},"
        for c in v["defaults"]
    ]
    L.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
