#!/usr/bin/env python3
"""Turns the specification's sharing test vectors into a C header for tests/share.c.

    python3 tests/vectors/sharing_to_c.py tests/vectors/sharing.json OUT.h

The build runs this; nothing it writes is checked in. Like the others here it only reformats:
every value in the header is copied from the JSON, none is computed.
"""

import json
import sys


def c_bytes(h):
    return "{" + ", ".join("0x" + h[i : i + 2] for i in range(0, len(h), 2)) + "}"


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    lines = [
        "/* Generated by tests/vectors/sharing_to_c.py from tests/vectors/sharing.json. Do not edit. */",
        "",
        "static const struct share_case cases[] = {",
    ]
    for c in v["cases"]:
        reads = ", ".join(json.dumps(r) for r in c["reads"])
        lines.append(
            f"    {{{c_bytes(c['address'])}, {json.dumps(c['text'])}, {json.dumps(c['base32'])}, "
            f"{json.dumps(c['link'])}, "
            f"{json.dumps(c['short_code'])}, {len(c['reads'])}, {{{reads}}}}},"
        )
    lines.append("};")
    lines.append("static const char *const refused[] = {")
    lines.extend(f"    {json.dumps(r)}," for r in v["refused"])
    lines.append("};")
    lines.append("static const char *const not_contacts[] = {")
    lines.extend(f"    {json.dumps(r['link'])}, /* {r['reason']} */" for r in v["not_contacts"])
    lines.append("};")
    lines.append("static const struct form_case forms[] = {")
    lines.extend(f"    {{{f['value']}ULL, {json.dumps(f['text'])}}}," for f in v["short_code_forms"])
    lines.append("};")
    lines.append("")
    open(out, "w", encoding="utf-8").write("\n".join(lines))


if __name__ == "__main__":
    main()
