#!/usr/bin/env python3
"""Turns the specification's unicast test vectors into a C header for tests/unicast.c.

    python3 tests/vectors/unicast_to_c.py tests/vectors/unicast-security.json OUT.h

The build runs this; nothing it writes is checked in. It only reformats: every value in the
header is copied from the JSON, none is computed, so the tests check the firmware against the
specification's numbers and not against anything worked out here.
"""

import json
import sys


def c_bytes(hex_str):
    b = bytes.fromhex(hex_str)
    if not b:
        return "NULL, 0"
    body = ", ".join(f"0x{x:02x}" for x in b)
    return f"(const uint8_t[]){{{body}}}, {len(b)}"


def c_array(hex_str, n):
    b = bytes.fromhex(hex_str)
    assert len(b) == n, (hex_str, n)
    return "{" + ", ".join(f"0x{x:02x}" for x in b) + "}"


def c_str(s):
    return json.dumps(s)


def main():
    src, out = sys.argv[1], sys.argv[2]
    v = json.load(open(src, encoding="utf-8"))
    lines = [
        "/* Generated by tests/vectors/unicast_to_c.py from tests/vectors/unicast-security.json."
        " Do not edit. */",
        "",
    ]

    lines.append("static const struct accepted_case accepted[] = {")
    for c in v["accepted"]:
        i = c["intermediate"]
        lines.append(
            f"    {{{c_str(c['name'])}, {c_array(c['session_secret'], 32)}, {c['direction']}, "
            f"{c['counter']}u, {c['hdr']}, {c['hops']}, {c['power']}, 0x{c['next']:08x}u, "
            f"0x{c['destination']:08x}u, {c_bytes(c['plaintext'])}, "
            f"{c_bytes(c['frame'])}, {c_array(i['epoch_key'], 32)}, {c_array(i['proof'], 4)}}},"
        )
    lines.append("};")

    lines.append("static const struct rejected_case rejected[] = {")
    for c in v["rejected"]:
        lines.append(
            f"    {{{c_str(c['name'])}, {c_array(c['session_secret'], 32)}, {c['direction']}, "
            f"{c['counter']}u, {c_bytes(c['frame'])}}},"
        )
    lines.append("};")

    lines.append("static const struct sequence_case sequences[] = {")
    for c in v["sequences"]:
        ds = []
        for d in c["deliveries"]:
            ack = (f"true, {c_array(d['proof'], 4)}" if d["acknowledge"]
                   else "false, {0}")
            if d["accept"]:
                ds.append(f"{{{c_bytes(d['frame'])}, true, {d['counter']}u, "
                          f"{c_bytes(d['plaintext'])}, {ack}}}")
            else:
                ds.append(f"{{{c_bytes(d['frame'])}, false, 0, NULL, 0, {ack}}}")
        lines.append(
            f"    {{{c_str(c['name'])}, {c_array(c['session_secret'], 32)}, {c['direction']}, "
            f"(const struct delivery[]){{{', '.join(ds)}}}, {len(ds)}}},"
        )
    lines.append("};")

    lines.append("static const struct collision_case collisions[] = {")
    for c in v["collisions"]:
        ss = ", ".join(f"{{{c_array(s['session_secret'], 32)}, {s['direction']}}}"
                       for s in c["sessions"])
        def acks(d):
            body = ", ".join(f"{{{a['session']}, {a['counter']}u, {c_array(a['proof'], 4)}}}"
                             for a in d["acknowledge"])
            return f"(const struct collision_ack[]){{{body}}}, {len(d['acknowledge'])}"

        ds = ", ".join(
            f"{{{c_bytes(d['frame'])}, true, {d['session']}, {d['counter']}u, "
            f"{c_bytes(d['plaintext'])}, {acks(d)}}}" if d["accept"] else
            f"{{{c_bytes(d['frame'])}, false, 0, 0, NULL, 0, {acks(d)}}}"
            for d in c["deliveries"]
        )
        lines.append(
            f"    {{{c_str(c['name'])}, (const struct collision_session[]){{{ss}}}, "
            f"{len(c['sessions'])}, (const struct collision_delivery[]){{{ds}}}, "
            f"{len(c['deliveries'])}}},"
        )
    lines.append("};")

    lines.append("static const struct sender_case senders[] = {")
    for c in v["senders"]:
        ss = ", ".join(
            f"{{{s['direction']}, {c_bytes(s['plaintext'])}, {s['counter']}u, "
            f"{c_bytes(s['frame'])}}}"
            for s in c["sends"]
        )
        lines.append(
            f"    {{{c_str(c['name'])}, {c_array(c['session_secret'], 32)}, "
            f"(const struct send[]){{{ss}}}, {len(c['sends'])}}},"
        )
    lines.append("};")

    lines.append("static const struct ack_case acknowledgements[] = {")
    for c in v["acknowledgements"]:
        lines.append(
            f"    {{{c_str(c['name'])}, {c_array(c['session_secret'], 32)}, {c['direction']}, "
            f"{c['counter']}u, {c_bytes(c['frame'])}, {'true' if c['valid'] else 'false'}}},"
        )
    lines.append("};")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
